In [2]:
import pandas as pd

## Series

In [6]:
import numpy as np
arr = np.arange(100,110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [7]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


## indexing

In [8]:
person = ['kim','lee','park','hong']
s = pd.Series(person)


In [9]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
s[-1]

# 파이선에서는 음수 인덱싱 o, 나머지 에서는 x 

KeyError: -1

In [14]:
s = pd.Series(person, index=['a','b','c','d'])
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [15]:
s['a']

'kim'

In [16]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [20]:
s.values

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [21]:
s.ndim

1

In [22]:
s.shape

(4,)

## NaN(Not A Number)

In [25]:
s = pd.Series(person + [np.nan])
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [27]:
arr = np.arange(50, 55 )
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [32]:
f = ['바나나',np.nan, '사과 ','포도', '복숭아']
s = pd.Series(f,index=list('가나다라마'))
print(s)

가    바나나
나    NaN
다    사과 
라     포도
마    복숭아
dtype: object


## 팬시 인덱싱

In [35]:
s[[2,3]]

C:\Users\이아랑\AppData\Local\Temp\ipykernel_39208\1527880992.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[2,3]]


다    사과 
라     포도
dtype: object

In [39]:
# s.iloc[[2,3]]
s[['다','나']]

다    사과 
나    NaN
dtype: object

## bool

In [65]:
s[[True,False]]

IndexError: Boolean index has wrong length: 2 instead of 9

In [64]:
s [a]

KeyError: "None of [Index(['바나나', '사과 ', '복숭아'], dtype='object')] are in the [index]"

In [45]:
arr = np.arange(5,20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [46]:
s[s<10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [51]:
s[s==5]

0    5
dtype: int64

## 결측치(NaN)처리

In [54]:
s= pd.Series([2,4,2,1,np.nan,2,4,8,np.nan])
print (s)

0    2.0
1    4.0
2    2.0
3    1.0
4    NaN
5    2.0
6    4.0
7    8.0
8    NaN
dtype: float64


In [56]:
s.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [59]:
s[s.isnull()]

4   NaN
8   NaN
dtype: float64

In [60]:
s[s.isna()]

4   NaN
8   NaN
dtype: float64

In [61]:
s[s.notnull()]

0    2.0
1    4.0
2    2.0
3    1.0
5    2.0
6    4.0
7    8.0
dtype: float64

In [62]:
s[1:3]

1    4.0
2    2.0
dtype: float64

## dataframe

In [67]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [69]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [70]:
df = pd.DataFrame(arr, colums=['가','나','다'],
    arr,
    colums=['가','나','다'],
    index=['a','b','c','d']
)

SyntaxError: positional argument follows keyword argument (1235609896.py, line 5)

In [71]:
data = {
    'name' : ['kim','lee','park'],
    'age' : [10,15,20],
    'location' : ['seoul','LA','tokyo']    
}
df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [72]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [73]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [74]:
df.values

array([['kim', 10, 'seoul'],
       ['lee', 15, 'LA'],
       ['park', 20, 'tokyo']], dtype=object)

In [75]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [76]:
df.T

0    1      2
name        kim  lee   park
age          10   15     20
location  seoul   LA  tokyo

In [79]:
df.index = list('abc')
df

name  age location
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo

### column

In [80]:
df['name']

a     kim
b     lee
c    park
Name: name, dtype: object

In [81]:
type(df['name'])

pandas.core.series.Series

In [82]:
df[['name','location']]

name location
a   kim    seoul
b   lee       LA
c  park    tokyo

In [83]:
type(df[['name','location']])

pandas.core.frame.DataFrame

In [86]:
df.rename(columns=({'location':'hometown'}))
df

name  age location
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo

In [90]:
df.rename(columns={'location':'hometown'},inplace=True)
df

name  age hometown
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo